[project]
name = 'Decentralized-Urban-Tree-Management'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.planting-coordination]
path = 'contracts/planting-coordination.clar'
clarity_version = 2
epoch = 2.5

[contracts.tree-registration]
path = 'contracts/tree-registration.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
